import Vue from 'vue'
import Vuex from 'vuex'
Vue.use(Vuex)
const banner1={
	state:{
		data:{
			picAd1:false,
			showModule:false,
			picNum:1,
			bannerPic:{
				a:null,
				b:null,
			}
		},
		verifyData:{
			verify:false,
			showModule:false,
			cell:{
				a:true,
				b:true,
				c:true,
				d:true,
			}
		}
		
	},
	mutations:{
		showPicAd1(state){
			state.data.picAd1=true;
		},
		delThis1(state){
			state.data.picAd1=false;
		},
		module(state,type){
			if(type=='picAd1'){
				state.verifyData.showModule=false;
				state.data.showModule=true;
			}
			if(type=='verify'){
				state.data.showModule=false;
				state.verifyData.showModule=true;
			}
		},
		addPicNum(state){
			if(state.data.picNum<=4){
				state.data.picNum++;
			}
		},
		setPic(state,data){
			if(data.type===1){
				state.data.bannerPic.a=data.url;
			}
			if(data.type===2){
				state.data.bannerPic.b=data.url;
			}
		},
		addVerify(state){
			if(!state.verifyData.verify){
				state.verifyData.verify=true;
			}
		},
		updateMessage(state,type){
			if(type==='a'){
				state.verifyData.cell.a=!state.verifyData.cell.a
			}
			if(type==='b'){
				state.verifyData.cell.b=!state.verifyData.cell.b
			}
			if(type==='c'){
				state.verifyData.cell.c=!state.verifyData.cell.c
			}
			if(type==='d'){
				state.verifyData.cell.c=!state.verifyData.cell.d
			}
		}
	},
	actions:{
		showPicAd1(context){
			context.commit('showPicAd1');
		},
		delThis1(context){
			context.commit('delThis1')
		},
		module(context,type){
			context.commit('module',type)
		},
		setPic(context,data){
			context.commit('setPic',data)
		},
		addPicNum(context){
			context.commit('addPicNum')
		},
		addVerify(context){
			context.commit('addVerify');
		}
	}
}
const store = new Vuex.Store({
	modules: {
		banner1:banner1
	}
})

export default store
